services:
  postgresql:
    image: postgres:16-alpine
    container_name: "pg"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "appdb"
      POSTGRES_USER: "appuser"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: {}
