version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: abc123
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  www:
    image: php:8.1-apache-buster
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
