version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: abc123
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:8.1.1-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
