version: "3.9"

volumes:
  datenbankdaten:
  code:

services:
  webserver:
    build: webserver
    ports:
      - 80:80
    volumes:
    - ./code:/var/www/html
    - ./webserver/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="root"
      - MYSOL_ROOT_PASSWORD="root"
    volumes:
      - datenbankdaten:/var/lib/mysql
